name: test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: mqtt-action
        uses: ./
        with:
          protocol: mqtt
          host: ${{secrets.SERVER}}
          port: 1883
          topic: ${{secrets.TOPIC}}
          message: ${{ github.sha }}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
